[package]
name = "core_video_editor"
version = "0.1.0"
edition = "2021"
authors=["NyanRus"]
readme="./README.md"
repository="https://github.com/nyanrus/core_video_editor"
license-file="./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.66"