[package]
name = "core_video_editor"
version = "0.1.0"
edition = "2021"
authors=["NyanRus"]
readme="./README.md"
repository="https://github.com/nyanrus/core_video_editor"
license-file="./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.66"
rayon = "1.5.3"
image = "0.24.3"
rgb = "0.8.33"
imageproc = {version="0.23.0",features = ["rayon"]}
serde_json = "1.0"
serde = "1.0"
ffmpeg-next = "5.0.3"
#photon-rs = "0.3.1"

#cargo vendor lines
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
#end of cargo vendor lines